<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $citiesAntoquia = [
            ['city_name' => 'Bogota D.C', 'departament_id' => 33],
            ['city_name' => 'Medellín', 'departament_id' => 2],
            ['city_name' => 'Abejorral', 'departament_id' => 2],
            ['city_name' => 'Abriaquí', 'departament_id' => 2],
            ['city_name' => 'Alejandría', 'departament_id' => 2],
            ['city_name' => 'Amagá', 'departament_id' => 2],
            ['city_name' => 'Amalfi', 'departament_id' => 2],
            ['city_name' => 'Andes', 'departament_id' => 2],
            ['city_name' => 'Angelópolis', 'departament_id' => 2],
            ['city_name' => 'Angostura', 'departament_id' => 2],
            ['city_name' => 'Anorí', 'departament_id' => 2],
            ['city_name' => 'Anza', 'departament_id' => 2],
            ['city_name' => 'Apartadó', 'departament_id' => 2],
            ['city_name' => 'Arboletes', 'departament_id' => 2],
            ['city_name' => 'Argelia', 'departament_id' => 2],
            ['city_name' => 'Armenia', 'departament_id' => 2],
            ['city_name' => 'Barbosa', 'departament_id' => 2],
            ['city_name' => 'Bello', 'departament_id' => 2],
            ['city_name' => 'Betania', 'departament_id' => 2],
            ['city_name' => 'Betulia', 'departament_id' => 2],
            ['city_name' => 'Ciudad Bolívar', 'departament_id' => 2],
            ['city_name' => 'Briceño', 'departament_id' => 2],
            ['city_name' => 'Buriticá', 'departament_id' => 2],
            ['city_name' => 'Cáceres', 'departament_id' => 2],
            ['city_name' => 'Caicedo', 'departament_id' => 2],
            ['city_name' => 'Caldas', 'departament_id' => 2],
            ['city_name' => 'Campamento', 'departament_id' => 2],
            ['city_name' => 'Cañasgordas', 'departament_id' => 2],
            ['city_name' => 'Caracolí', 'departament_id' => 2],
            ['city_name' => 'Caramanta', 'departament_id' => 2],
            ['city_name' => 'Carepa', 'departament_id' => 2],
            ['city_name' => 'Carolina', 'departament_id' => 2],
            ['city_name' => 'Caucasia', 'departament_id' => 2],
            ['city_name' => 'Chigorodó', 'departament_id' => 2],
            ['city_name' => 'Cisneros', 'departament_id' => 2],
            ['city_name' => 'Cocorná', 'departament_id' => 2],
            ['city_name' => 'Concepción', 'departament_id' => 2],
            ['city_name' => 'Concordia', 'departament_id' => 2],
            ['city_name' => 'Copacabana', 'departament_id' => 2],
            ['city_name' => 'Dabeiba', 'departament_id' => 2],
            ['city_name' => 'Don Matías', 'departament_id' => 2],
            ['city_name' => 'Ebéjico', 'departament_id' => 2],
            ['city_name' => 'El Bagre', 'departament_id' => 2],
            ['city_name' => 'Entrerrios', 'departament_id' => 2],
            ['city_name' => 'Envigado', 'departament_id' => 2],
            ['city_name' => 'Fredonia', 'departament_id' => 2],
            ['city_name' => 'Giraldo', 'departament_id' => 2],
            ['city_name' => 'Girardota', 'departament_id' => 2],
            ['city_name' => 'Gómez Plata', 'departament_id' => 2],
            ['city_name' => 'Guadalupe', 'departament_id' => 2],
            ['city_name' => 'Guarne', 'departament_id' => 2],
            ['city_name' => 'Guatapé', 'departament_id' => 2],
            ['city_name' => 'Heliconia', 'departament_id' => 2],
            ['city_name' => 'Hispania', 'departament_id' => 2],
            ['city_name' => 'Itagüí', 'departament_id' => 2],
            ['city_name' => 'Ituango', 'departament_id' => 2],
            ['city_name' => 'Jardín', 'departament_id' => 2],
            ['city_name' => 'Jericó', 'departament_id' => 2],
            ['city_name' => 'La Ceja', 'departament_id' => 2],
            ['city_name' => 'La Estrella', 'departament_id' => 2],
            ['city_name' => 'La Pintada', 'departament_id' => 2],
            ['city_name' => 'La Unión', 'departament_id' => 2],
            ['city_name' => 'Liborina', 'departament_id' => 2],
            ['city_name' => 'Maceo', 'departament_id' => 2],
            ['city_name' => 'Marinilla', 'departament_id' => 2],
            ['city_name' => 'Montebello', 'departament_id' => 2],
            ['city_name' => 'Murindó', 'departament_id' => 2],
            ['city_name' => 'Mutatá', 'departament_id' => 2],
            ['city_name' => 'Nariño', 'departament_id' => 2],
            ['city_name' => 'Necoclí', 'departament_id' => 2],
            ['city_name' => 'Nechí', 'departament_id' => 2],
            ['city_name' => 'Olaya', 'departament_id' => 2],
            ['city_name' => 'Peñol', 'departament_id' => 2],
            ['city_name' => 'Peque', 'departament_id' => 2],
            ['city_name' => 'Pueblorrico', 'departament_id' => 2],
            ['city_name' => 'Puerto Berrío', 'departament_id' => 2],
            ['city_name' => 'Puerto Nare', 'departament_id' => 2],
            ['city_name' => 'Puerto Triunfo', 'departament_id' => 2],
            ['city_name' => 'Remedios', 'departament_id' => 2],
            ['city_name' => 'Retiro', 'departament_id' => 2],
            ['city_name' => 'Rionegro', 'departament_id' => 2],
            ['city_name' => 'Sabanalarga', 'departament_id' => 2],
            ['city_name' => 'Sabaneta', 'departament_id' => 2],
            ['city_name' => 'Salgar', 'departament_id' => 2],
            ['city_name' => 'San Andrés', 'departament_id' => 2],
            ['city_name' => 'San Carlos', 'departament_id' => 2],
            ['city_name' => 'San Francisco', 'departament_id' => 2],
            ['city_name' => 'San Jerónimo', 'departament_id' => 2],
            ['city_name' => 'San José de la Montaña', 'departament_id' => 2],
            ['city_name' => 'San Juan de Urabá', 'departament_id' => 2],
            ['city_name' => 'San Luis', 'departament_id' => 2],
            ['city_name' => 'San Pedro de los Milagros', 'departament_id' => 2],
            ['city_name' => 'San Pedro de Urabá', 'departament_id' => 2],
            ['city_name' => 'San Rafael', 'departament_id' => 2],
            ['city_name' => 'San Roque', 'departament_id' => 2],
            ['city_name' => 'San Vicente', 'departament_id' => 2],
            ['city_name' => 'Santa Bárbara', 'departament_id' => 2],
            ['city_name' => 'Santa Fe de Antioquia', 'departament_id' => 2],
            ['city_name' => 'Santa Rosa de Osos', 'departament_id' => 2],
            ['city_name' => 'Santo Domingo', 'departament_id' => 2],
            ['city_name' => 'El Santuario', 'departament_id' => 2],
            ['city_name' => 'Segovia', 'departament_id' => 2],
            ['city_name' => 'Sonsón', 'departament_id' => 2],
            ['city_name' => 'Sopetrán', 'departament_id' => 2],
            ['city_name' => 'Támesis', 'departament_id' => 2],
            ['city_name' => 'Tarazá', 'departament_id' => 2],
            ['city_name' => 'Tarso', 'departament_id' => 2],
            ['city_name' => 'Titiribí', 'departament_id' => 2],
            ['city_name' => 'Toledo', 'departament_id' => 2],
            ['city_name' => 'Turbo', 'departament_id' => 2],
            ['city_name' => 'Uramita', 'departament_id' => 2],
            ['city_name' => 'Urrao', 'departament_id' => 2],
            ['city_name' => 'Valdivia', 'departament_id' => 2],
            ['city_name' => 'Valparaíso', 'departament_id' => 2],
            ['city_name' => 'Vegachí', 'departament_id' => 2],
            ['city_name' => 'Venecia', 'departament_id' => 2],
            ['city_name' => 'Vigía del Fuerte', 'departament_id' => 2],
            ['city_name' => 'Yalí', 'departament_id' => 2],
            ['city_name' => 'Yarumal', 'departament_id' => 2],
            ['city_name' => 'Yolombó', 'departament_id' => 2],
            ['city_name' => 'Yondó', 'departament_id' => 2],
            ['city_name' => 'Zaragoza', 'departament_id' => 2]
        ];

        DB::table('cities')->insert($citiesAntoquia);

        $citiesAmazonas = [
            [
                'city_name' => 'Leticia',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'El Encanto',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'La Chorrera',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'La Pedrera',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'La Victoria',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'Puerto Arica',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'Puerto Nariño',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'Puerto Santander',
                'departament_id' => 1,
            ],
            [
                'city_name' => 'Tarapacá',
                'departament_id' => 1,
            ],
        ];

        DB::table('cities')->insert($citiesAmazonas);


        $citiesArauca = [
            [
                'city_name' => 'Arauquita',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Cravo Norte',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Fortul',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Puerto Rondón',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Saravena',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Tame',
                'departament_id' => 3,
            ],
            [
                'city_name' => 'Arauca',
                'departament_id' => 3,
            ],
        ];

        DB::table('cities')->insert($citiesArauca);

        $citiesAtlantico = [
            [
                'city_name' => 'Barranquilla',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Baranoa',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Candelaria',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Galapa',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Luruaco',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Malambo',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Manatí',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Piojó',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Polonuevo',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Sabanagrande',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Sabanalarga',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Santa Lucía',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Santo Tomás',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Soledad',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Suan',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Tubará',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Usiacurí',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Juan de Acosta',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Palmar de Varela',
                'departament_id' => 4,
            ],
            [
                'city_name' => 'Campo de La Cruz',
                'departament_id' => 4,
            ],
        ];

        DB::table('cities')->insert($citiesAtlantico);

        $citiesBolivar = [
            [
                'city_name' => 'Cartagena',
                'departament_id' => 5
            ],
            [
                'city_name' => 'Achí',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Arenal',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Arjona',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Arroyohondo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Calamar',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Cantagallo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Cicuco',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Córdoba',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Clemencia',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'El Guamo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Magangué',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Mahates',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Margarita',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Montecristo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Mompós',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Morales',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Norosí',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Pinillos',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Regidor',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Río Viejo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Estanislao',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Fernando',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Juan Nepomuceno',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Santa Catalina',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Santa Rosa',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Simití',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Soplaviento',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Talaigua Nuevo',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Tiquisio',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Turbaco',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Turbaná',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Villanueva',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Barranco de Loba',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Santa Rosa del Sur',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Hatillo de Loba',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'El Carmen de Bolívar',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Martín de Loba',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'Altos del Rosario',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Jacinto del Cauca',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Pablo de Borbur',
                'departament_id' => 5,
            ],
            [
                'city_name' => 'San Jacinto',
                'departament_id' => 5,
            ],
        ];

        DB::table('cities')->insert($citiesBolivar);

        $citiesBoyaca = [
            ["city_name" => "Tununguá", "departament_id" => 6],
            ["city_name" => "Motavita", "departament_id" => 6],
            ["city_name" => "Ciénega", "departament_id" => 6],
            ["city_name" => "Tunja", "departament_id" => 6],
            ["city_name" => "Almeida", "departament_id" => 6],
            ["city_name" => "Aquitania", "departament_id" => 6],
            ["city_name" => "Arcabuco", "departament_id" => 6],
            ["city_name" => "Berbeo", "departament_id" => 6],
            ["city_name" => "Betéitiva", "departament_id" => 6],
            ["city_name" => "Boavita", "departament_id" => 6],
            ["city_name" => "Boyacá", "departament_id" => 6],
            ["city_name" => "Briceño", "departament_id" => 6],
            ["city_name" => "Buena Vista", "departament_id" => 6],
            ["city_name" => "Busbanzá", "departament_id" => 6],
            ["city_name" => "Caldas", "departament_id" => 6],
            ["city_name" => "Campohermoso", "departament_id" => 6],
            ["city_name" => "Cerinza", "departament_id" => 6],
            ["city_name" => "Chinavita", "departament_id" => 6],
            ["city_name" => "Chiquinquirá", "departament_id" => 6],
            ["city_name" => "Chiscas", "departament_id" => 6],
            ["city_name" => "Chita", "departament_id" => 6],
            ["city_name" => "Chitaraque", "departament_id" => 6],
            ["city_name" => "Chivatá", "departament_id" => 6],
            ["city_name" => "Cómbita", "departament_id" => 6],
            ["city_name" => "Coper", "departament_id" => 6],
            ["city_name" => "Corrales", "departament_id" => 6],
            ["city_name" => "Covarachía", "departament_id" => 6],
            ["city_name" => "Cubará", "departament_id" => 6],
            ["city_name" => "Cucaita", "departament_id" => 6],
            ["city_name" => "Cuítiva", "departament_id" => 6],
            ["city_name" => "Chíquiza", "departament_id" => 6],
            ["city_name" => "Chivor", "departament_id" => 6],
            ["city_name" => "Duitama", "departament_id" => 6],
            ["city_name" => "El Cocuy", "departament_id" => 6],
            ["city_name" => "El Espino", "departament_id" => 6],
            ["city_name" => "Firavitoba", "departament_id" => 6],
            ["city_name" => "Floresta", "departament_id" => 6],
            ["city_name" => "Gachantivá", "departament_id" => 6],
            ["city_name" => "Gameza", "departament_id" => 6],
            ["city_name" => "Garagoa", "departament_id" => 6],
            ["city_name" => "Guacamayas", "departament_id" => 6],
            ["city_name" => "Guateque", "departament_id" => 6],
            ["city_name" => "Guayatá", "departament_id" => 6],
            ["city_name" => "Güicán", "departament_id" => 6],
            ["city_name" => "Iza", "departament_id" => 6],
            ["city_name" => "Jenesano", "departament_id" => 6],
            ["city_name" => "Jericó", "departament_id" => 6],
            ["city_name" => "Labranzagrande", "departament_id" => 6],
            ["city_name" => "La Capilla", "departament_id" => 6],
            ["city_name" => "La Victoria", "departament_id" => 6],
            ["city_name" => "Macanal", "departament_id" => 6],
            ["city_name" => "Maripí", "departament_id" => 6],
            ["city_name" => "Miraflores", "departament_id" => 6],
            ["city_name" => "Mongua", "departament_id" => 6],
            ["city_name" => "Monguí", "departament_id" => 6],
            ["city_name" => "Moniquirá", "departament_id" => 6],
            ["city_name" => "Muzo", "departament_id" => 6],
            ["city_name" => "Nobsa", "departament_id" => 6],
            ["city_name" => "Nuevo Colón", "departament_id" => 6],
            ["city_name" => "Oicatá", "departament_id" => 6],
            ["city_name" => "Otanche", "departament_id" => 6],
            ["city_name" => "Pachavita", "departament_id" => 6],
            ["city_name" => "Páez", "departament_id" => 6],
            ["city_name" => "Paipa", "departament_id" => 6],
            ["city_name" => "Pajarito", "departament_id" => 6],
            ["city_name" => "Panqueba", "departament_id" => 6],
            ["city_name" => "Pauna", "departament_id" => 6],
            ["city_name" => "Paya", "departament_id" => 6],
            ["city_name" => "Pesca", "departament_id" => 6],
            ["city_name" => "Pisba", "departament_id" => 6],
            ["city_name" => "Puerto Boyacá", "departament_id" => 6],
            ["city_name" => "Quípama", "departament_id" => 6],
            ["city_name" => "Ramiriquí", "departament_id" => 6],
            ["city_name" => "Ráquira", "departament_id" => 6],
            ["city_name" => "Rondón", "departament_id" => 6],
            ["city_name" => "Saboyá", "departament_id" => 6],
            ["city_name" => "Sáchica", "departament_id" => 6],
            ["city_name" => "Samacá", "departament_id" => 6],
            ["city_name" => "San Eduardo", "departament_id" => 6],
            ["city_name" => "San José de Pare", "departament_id" => 6],
            ["city_name" => "San Luis de Gaceno", "departament_id" => 6],
            ["city_name" => "San Mateo", "departament_id" => 6],
            ["city_name" => "San Miguel de Sema", "departament_id" => 6],
            ["city_name" => "San Pablo de Borbur", "departament_id" => 6],
            ["city_name" => "Santa María", "departament_id" => 6],
            ["city_name" => "Santa Rosa de Viterbo", "departament_id" => 6],
            ["city_name" => "Santa Sofía", "departament_id" => 6],
            ["city_name" => "Santana", "departament_id" => 6],
            ["city_name" => "Sativanorte", "departament_id" => 6],
            ["city_name" => "Sativasur", "departament_id" => 6],
            ["city_name" => "Siachoque", "departament_id" => 6],
            ["city_name" => "Soatá", "departament_id" => 6],
            ["city_name" => "Socha", "departament_id" => 6],
            ["city_name" => "Socotá", "departament_id" => 6],
            ["city_name" => "Sogamoso", "departament_id" => 6],
            ["city_name" => "Somondoco", "departament_id" => 6],
            ["city_name" => "Sora", "departament_id" => 6],
            ["city_name" => "Soracá", "departament_id" => 6],
            ["city_name" => "Sotaquirá", "departament_id" => 6],
            ["city_name" => "Susacón", "departament_id" => 6],
            ["city_name" => "Sutamarchán", "departament_id" => 6],
            ["city_name" => "Sutatenza", "departament_id" => 6],
            ["city_name" => "Tasco", "departament_id" => 6],
            ["city_name" => "Tenza", "departament_id" => 6],
            ["city_name" => "Tibaná", "departament_id" => 6],
            ["city_name" => "Tibasosa", "departament_id" => 6],
            ["city_name" => "Tinjacá", "departament_id" => 6],
            ["city_name" => "Tipacoque", "departament_id" => 6],
            ["city_name" => "Toca", "departament_id" => 6],
            ["city_name" => "Togüí", "departament_id" => 6],
            ["city_name" => "Topagá", "departament_id" => 6],
            ["city_name" => "Tota", "departament_id" => 6],
            ["city_name" => "Tunja", "departament_id" => 6],
            ["city_name" => "Turmequé", "departament_id" => 6],
            ["city_name" => "Tuta", "departament_id" => 6],
            ["city_name" => "Tutazá", "departament_id" => 6],
            ["city_name" => "Umbita", "departament_id" => 6],
            ["city_name" => "Ventaquemada", "departament_id" => 6],
            ["city_name" => "Viracachá", "departament_id" => 6],
            ["city_name" => "Zetaquira", "departament_id" => 6]
        ];

        DB::table('cities')->insert($citiesBoyaca);


        $citiesCaldas = [
            ["city_name" => "Manizales", "departament_id" => 7],
            ["city_name" => "Aguadas", "departament_id" => 7],
            ["city_name" => "Anserma", "departament_id" => 7],
            ["city_name" => "Aranzazu", "departament_id" => 7],
            ["city_name" => "Belalcázar", "departament_id" => 7],
            ["city_name" => "Chinchiná", "departament_id" => 7],
            ["city_name" => "Filadelfia", "departament_id" => 7],
            ["city_name" => "La Dorada", "departament_id" => 7],
            ["city_name" => "La Merced", "departament_id" => 7],
            ["city_name" => "Manzanares", "departament_id" => 7],
            ["city_name" => "Marmato", "departament_id" => 7],
            ["city_name" => "Marulanda", "departament_id" => 7],
            ["city_name" => "Neira", "departament_id" => 7],
            ["city_name" => "Norcasia", "departament_id" => 7],
            ["city_name" => "Pácora", "departament_id" => 7],
            ["city_name" => "Palestina", "departament_id" => 7],
            ["city_name" => "Pensilvania", "departament_id" => 7],
            ["city_name" => "Riosucio", "departament_id" => 7],
            ["city_name" => "Risaralda", "departament_id" => 7],
            ["city_name" => "Salamina", "departament_id" => 7],
            ["city_name" => "Samaná", "departament_id" => 7],
            ["city_name" => "San José", "departament_id" => 7],
            ["city_name" => "Supía", "departament_id" => 7],
            ["city_name" => "Victoria", "departament_id" => 7],
            ["city_name" => "Villamaría", "departament_id" => 7],
            ["city_name" => "Viterbo", "departament_id" => 7]
        ];
        

        DB::table('cities')->insert($citiesCaldas);

        $citiesCaqueta = [
            ["city_name" => "Florencia", "departament_id" => 8],
            ["city_name" => "Albania", "departament_id" => 8],
            ["city_name" => "Curillo", "departament_id" => 8],
            ["city_name" => "El Doncello", "departament_id" => 8],
            ["city_name" => "El Paujil", "departament_id" => 8],
            ["city_name" => "Morelia", "departament_id" => 8],
            ["city_name" => "Puerto Rico", "departament_id" => 8],
            ["city_name" => "Solano", "departament_id" => 8],
            ["city_name" => "Solita", "departament_id" => 8],
            ["city_name" => "Valparaíso", "departament_id" => 8],
            ["city_name" => "San José del Fragua", "departament_id" => 8],
            ["city_name" => "Belén de Los Andaquies", "departament_id" => 8],
            ["city_name" => "Cartagena del Chairá", "departament_id" => 8]
        ];
        
        DB::table('cities')->insert($citiesCaqueta);

        $citiesCasanare = [
            ["city_name" => "Yopal", "departament_id" => 9],
            ["city_name" => "Aguazul", "departament_id" => 9],
            ["city_name" => "Chámeza", "departament_id" => 9],
            ["city_name" => "Hato Corozal", "departament_id" => 9],
            ["city_name" => "La Salina", "departament_id" => 9],
            ["city_name" => "Monterrey", "departament_id" => 9],
            ["city_name" => "Pore", "departament_id" => 9],
            ["city_name" => "Recetor", "departament_id" => 9],
            ["city_name" => "Sabanalarga", "departament_id" => 9],
            ["city_name" => "Sácama", "departament_id" => 9],
            ["city_name" => "Tauramena", "departament_id" => 9],
            ["city_name" => "Trinidad", "departament_id" => 9],
            ["city_name" => "Villanueva", "departament_id" => 9],
            ["city_name" => "San Luis de Gaceno", "departament_id" => 9],
            ["city_name" => "Paz de Ariporo", "departament_id" => 9]
        ];

        DB::table('cities')->insert($citiesCasanare);

        $citiesCauca = [
            ["city_name" => "Popayán", "departament_id" => 10],
            ["city_name" => "Almaguer", "departament_id" => 10],
            ["city_name" => "Argelia", "departament_id" => 10],
            ["city_name" => "Balboa", "departament_id" => 10],
            ["city_name" => "Bolívar", "departament_id" => 10],
            ["city_name" => "Buenos Aires", "departament_id" => 10],
            ["city_name" => "Cajibío", "departament_id" => 10],
            ["city_name" => "Caldono", "departament_id" => 10],
            ["city_name" => "Caloto", "departament_id" => 10],
            ["city_name" => "Corinto", "departament_id" => 10],
            ["city_name" => "El Tambo", "departament_id" => 10],
            ["city_name" => "Florencia", "departament_id" => 10],
            ["city_name" => "Guachené", "departament_id" => 10],
            ["city_name" => "Guapi", "departament_id" => 10],
            ["city_name" => "Inzá", "departament_id" => 10],
            ["city_name" => "Jambaló", "departament_id" => 10],
            ["city_name" => "La Sierra", "departament_id" => 10],
            ["city_name" => "La Vega", "departament_id" => 10],
            ["city_name" => "López", "departament_id" => 10],
            ["city_name" => "Mercaderes", "departament_id" => 10],
            ["city_name" => "Miranda", "departament_id" => 10],
            ["city_name" => "Morales", "departament_id" => 10],
            ["city_name" => "Padilla", "departament_id" => 10],
            ["city_name" => "Patía", "departament_id" => 10],
            ["city_name" => "Piamonte", "departament_id" => 10],
            ["city_name" => "Piendamó", "departament_id" => 10],
            ["city_name" => "Puerto Tejada", "departament_id" => 10],
            ["city_name" => "Puracé", "departament_id" => 10],
            ["city_name" => "Rosas", "departament_id" => 10],
            ["city_name" => "Santa Rosa", "departament_id" => 10],
            ["city_name" => "Silvia", "departament_id" => 10],
            ["city_name" => "Sotara", "departament_id" => 10],
            ["city_name" => "Suárez", "departament_id" => 10],
            ["city_name" => "Sucre", "departament_id" => 10],
            ["city_name" => "Timbío", "departament_id" => 10],
            ["city_name" => "Timbiquí", "departament_id" => 10],
            ["city_name" => "Toribio", "departament_id" => 10],
            ["city_name" => "Totoró", "departament_id" => 10],
            ["city_name" => "Villa Rica", "departament_id" => 10],
            ["city_name" => "Santander de Quilichao", "departament_id" => 10],
            ["city_name" => "San Sebastián", "departament_id" => 10]
        ];

        
        DB::table('cities')->insert($citiesCauca);

        $citiesCesar = [
            ["city_name" => "Valledupar", "departament_id" => 11],
            ["city_name" => "Aguachica", "departament_id" => 11],
            ["city_name" => "Agustín Codazzi", "departament_id" => 11],
            ["city_name" => "Astrea", "departament_id" => 11],
            ["city_name" => "Becerril", "departament_id" => 11],
            ["city_name" => "Bosconia", "departament_id" => 11],
            ["city_name" => "Chimichagua", "departament_id" => 11],
            ["city_name" => "Chiriguaná", "departament_id" => 11],
            ["city_name" => "Curumaní", "departament_id" => 11],
            ["city_name" => "El Copey", "departament_id" => 11],
            ["city_name" => "El Paso", "departament_id" => 11],
            ["city_name" => "Gamarra", "departament_id" => 11],
            ["city_name" => "González", "departament_id" => 11],
            ["city_name" => "La Gloria", "departament_id" => 11],
            ["city_name" => "Manaure", "departament_id" => 11],
            ["city_name" => "Pailitas", "departament_id" => 11],
            ["city_name" => "Pelaya", "departament_id" => 11],
            ["city_name" => "Pueblo Bello", "departament_id" => 11],
            ["city_name" => "La Paz", "departament_id" => 11],
            ["city_name" => "San Alberto", "departament_id" => 11],
            ["city_name" => "San Diego", "departament_id" => 11],
            ["city_name" => "San Martín", "departament_id" => 11],
            ["city_name" => "Tamalameque", "departament_id" => 11],
            ["city_name" => "Río de Oro", "departament_id" => 11],
            ["city_name" => "La Jagua de Ibirico", "departament_id" => 11]
        ];

        
        DB::table('cities')->insert($citiesCesar);

        $citiesChoco = [
            ["city_name" => "Istmina", "departament_id" => 12],
            ["city_name" => "Quibdó", "departament_id" => 12],
            ["city_name" => "Acandí", "departament_id" => 12],
            ["city_name" => "Alto Baudo", "departament_id" => 12],
            ["city_name" => "Atrato", "departament_id" => 12],
            ["city_name" => "Bagadó", "departament_id" => 12],
            ["city_name" => "Bahía Solano", "departament_id" => 12],
            ["city_name" => "Bajo Baudó", "departament_id" => 12],
            ["city_name" => "Bojaya", "departament_id" => 12],
            ["city_name" => "Cértegui", "departament_id" => 12],
            ["city_name" => "Condoto", "departament_id" => 12],
            ["city_name" => "Juradó", "departament_id" => 12],
            ["city_name" => "Lloró", "departament_id" => 12],
            ["city_name" => "Medio Atrato", "departament_id" => 12],
            ["city_name" => "Medio Baudó", "departament_id" => 12],
            ["city_name" => "Medio San Juan", "departament_id" => 12],
            ["city_name" => "Nóvita", "departament_id" => 12],
            ["city_name" => "Nuquí", "departament_id" => 12],
            ["city_name" => "Río Iro", "departament_id" => 12],
            ["city_name" => "Río Quito", "departament_id" => 12],
            ["city_name" => "Riosucio", "departament_id" => 12],
            ["city_name" => "Sipí", "departament_id" => 12],
            ["city_name" => "Unguía", "departament_id" => 12],
            ["city_name" => "El Litoral del San Juan", "departament_id" => 12],
            ["city_name" => "El Cantón del San Pablo", "departament_id" => 12],
            ["city_name" => "El Carmen de Atrato", "departament_id" => 12],
            ["city_name" => "San José del Palmar", "departament_id" => 12],
            ["city_name" => "Belén de Bajira", "departament_id" => 12]
        ];
        
        DB::table('cities')->insert($citiesChoco);

        $citiesCordoba = [
            ["city_name" => "San Bernardo del Viento", "departament_id" => 13],
            ["city_name" => "Montería", "departament_id" => 13],
            ["city_name" => "Ayapel", "departament_id" => 13],
            ["city_name" => "Buenavista", "departament_id" => 13],
            ["city_name" => "Canalete", "departament_id" => 13],
            ["city_name" => "Cereté", "departament_id" => 13],
            ["city_name" => "Chimá", "departament_id" => 13],
            ["city_name" => "Chinú", "departament_id" => 13],
            ["city_name" => "Cotorra", "departament_id" => 13],
            ["city_name" => "Lorica", "departament_id" => 13],
            ["city_name" => "Los Córdobas", "departament_id" => 13],
            ["city_name" => "Momil", "departament_id" => 13],
            ["city_name" => "Moñitos", "departament_id" => 13],
            ["city_name" => "Planeta Rica", "departament_id" => 13],
            ["city_name" => "Pueblo Nuevo", "departament_id" => 13],
            ["city_name" => "Puerto Escondido", "departament_id" => 13],
            ["city_name" => "Purísima", "departament_id" => 13],
            ["city_name" => "Sahagún", "departament_id" => 13],
            ["city_name" => "San Andrés Sotavento", "departament_id" => 13],
            ["city_name" => "San Antero", "departament_id" => 13],
            ["city_name" => "San Pelayo", "departament_id" => 13],
            ["city_name" => "Tierralta", "departament_id" => 13],
            ["city_name" => "Tuchín", "departament_id" => 13],
            ["city_name" => "Valencia", "departament_id" => 13],
            ["city_name" => "San José de Uré", "departament_id" => 13],
            ["city_name" => "Ciénaga de Oro", "departament_id" => 13],
            ["city_name" => "San Carlos", "departament_id" => 13]
        ];
        
        DB::table('cities')->insert($citiesCordoba);
        

        $cundinamarcaCities = [
            ["city_name" => "Anolaima", "departament_id" => 14],
            ["city_name" => "Anapoima", "departament_id" => 14],
            ["city_name" => "Arbeláez", "departament_id" => 14],
            ["city_name" => "Beltrán", "departament_id" => 14],
            ["city_name" => "Bituima", "departament_id" => 14],
            ["city_name" => "Bojacá", "departament_id" => 14],
            ["city_name" => "Cabrera", "departament_id" => 14],
            ["city_name" => "Cachipay", "departament_id" => 14],
            ["city_name" => "Cajicá", "departament_id" => 14],
            ["city_name" => "Caparrapí", "departament_id" => 14],
            ["city_name" => "Caqueza", "departament_id" => 14],
            ["city_name" => "Chaguaní", "departament_id" => 14],
            ["city_name" => "Chipaque", "departament_id" => 14],
            ["city_name" => "Choachí", "departament_id" => 14],
            ["city_name" => "Chocontá", "departament_id" => 14],
            ["city_name" => "Cogua", "departament_id" => 14],
            ["city_name" => "Cota", "departament_id" => 14],
            ["city_name" => "Cucunubá", "departament_id" => 14],
            ["city_name" => "El Colegio", "departament_id" => 14],
            ["city_name" => "El Rosal", "departament_id" => 14],
            ["city_name" => "Fomeque", "departament_id" => 14],
            ["city_name" => "Fosca", "departament_id" => 14],
            ["city_name" => "Funza", "departament_id" => 14],
            ["city_name" => "Fúquene", "departament_id" => 14],
            ["city_name" => "Fusagasuga", "departament>id" => 14],
            ["city_name" => "Gachala", "departament_id" => 14],
            ["city_name" => "Gachancipá", "departament_id" => 14],
            ["city_name" => "Gachetá", "departament_id" => 14],
            ["city_name" => "Girardot", "departament_id" => 14],
            ["city_name" => "Granada", "departament_id" => 14],
            ["city_name" => "Guachetá", "departament_id" => 14],
            ["city_name" => "Guaduas", "departament_id" => 14],
            ["city_name" => "Guasca", "departament_id" => 14],
            ["city_name" => "Guataquí", "departament_id" => 14],
            ["city_name" => "Guatavita", "departament_id" => 14],
            ["city_name" => "Guayabetal", "departament_id" => 14],
            ["city_name" => "Gutiérrez", "departament_id" => 14],
            ["city_name" => "Jerusalén", "departament_id" => 14],
            ["city_name" => "Junín", "departament_id" => 14],
            ["city_name" => "La Calera", "departament_id" => 14],
            ["city_name" => "La Mesa", "departament_id" => 14],
            ["city_name" => "La Palma", "departament_id" => 14],
            ["city_name" => "La Peña", "departament_id" => 14],
            ["city_name" => "La Vega", "departament_id" => 14],
            ["city_name" => "Lenguazaque", "departament_id" => 14],
            ["city_name" => "Macheta", "departament_id" => 14],
            ["city_name" => "Madrid", "departament_id" => 14],
            ["city_name" => "Manta", "departament_id" => 14],
            ["city_name" => "Medina", "departament_id" => 14],
            ["city_name" => "Mosquera", "departament_id" => 14],
            ["city_name" => "Nariño", "departament_id" => 14],
            ["city_name" => "Nemocón", "departament_id" => 14],
            ["city_name" => "Nilo", "departament_id" => 14],
            ["city_name" => "Nimaima", "departament_id" => 14],
            ["city_name" => "Nocaima", "departament_id" => 14],
            ["city_name" => "Venecia", "departament_id" => 14],
            ["city_name" => "Pacho", "departament_id" => 14],
            ["city_name" => "Paime", "departament_id" => 14],
            ["city_name" => "Pandi", "departament_id" => 14],
            ["city_name" => "Paratebueno", "departament_id" => 14],
            ["city_name" => "Pasca", "departament_id" => 14],
            ["city_name" => "Puerto Salgar", "departament_id" => 14],
            ["city_name" => "Pulí", "departament_id" => 14],
            ["city_name" => "Quebradanegra", "departament_id" => 14],
            ["city_name" => "Quetame", "departament_id" => 14],
            ["city_name" => "Quipile", "departament_id" => 14],
            ["city_name" => "Apulo", "departament_id" => 14],
            ["city_name" => "Ricaurte", "departament_id" => 14],
            ["city_name" => "San Bernardo", "departament_id" => 14],
            ["city_name" => "San Cayetano", "departament_id" => 14],
            ["city_name" => "San Francisco", "departament_id" => 14],
            ["city_name" => "Sesquilé", "departament_id" => 14],
            ["city_name" => "Sibaté", "departament_id" => 14],
            ["city_name" => "Silvania", "departament_id" => 14],
            ["city_name" => "Simijaca", "departament_id" => 14],
            ["city_name" => "Soacha", "departament_id" => 14],
            ["city_name" => "Subachoque", "departament_id" => 14],
            ["city_name" => "Suesca", "departament_id" => 14],
            ["city_name" => "Supatá", "departament_id" => 14],
            ["city_name" => "Susa", "departament_id" => 14],
            ["city_name" => "Sutatausa", "departament_id" => 14],
            ["city_name" => "Tabio", "departament_id" => 14],
            ["city_name" => "Tausa", "departament_id" => 14],
            ["city_name" => "Tena", "departament_id" => 14],
            ["city_name" => "Tenjo", "departament_id" => 14],
            ["city_name" => "Tibacuy", "departament_id" => 14],
            ["city_name" => "Tibirita", "departament_id" => 14],
            ["city_name" => "Tocaima", "departament_id" => 14],
            ["city_name" => "Tocancipá", "departament_id" => 14],
            ["city_name" => "Topaipí", "departament_id" => 14],
            ["city_name" => "Ubalá", "departament_id" => 14],
            ["city_name" => "Ubaque", "departament_id" => 14],
            ["city_name" => "Une", "departament_id" => 14],
            ["city_name" => "Útica", "departament_id" => 14],
            ["city_name" => "Vianí", "departament_id" => 14],
            ["city_name" => "Villagómez", "departament_id" => 14],
            ["city_name" => "Villapinzón", "departament_id" => 14],
            ["city_name" => "Villeta", "departament_id" => 14],
            ["city_name" => "Viotá", "departament_id" => 14],
            ["city_name" => "Zipacón", "departament_id" => 14],
            ["city_name" => "San Juan de Río Seco", "departament_id" => 14],
            ["city_name" => "Villa de San Diego de Ubate", "departament_id" => 14],
            ["city_name" => "Guayabal de Siquima", "departament_id" => 14],
            ["city_name" => "San Antonio del Tequendama", "departament_id" => 14],
            ["city_name" => "Agua de Dios", "departament_id" => 14],
            ["city_name" => "Carmen de Carupa", "departament_id" => 14],
            ["city_name" => "Vergara", "departament_id" => 14]
        ];
        

        DB::table('cities')->insert($cundinamarcaCities);


        $guainiaCities = [
            ["city_name" => "Inírida", "departament_id" => 15],
            ["city_name" => "Barranco Minas", "departament_id" => 15],
            ["city_name" => "Mapiripana", "departament_id" => 15],
            ["city_name" => "San Felipe", "departament_id" => 15],
            ["city_name" => "Puerto Colombia", "departament_id" => 15],
            ["city_name" => "La Guadalupe", "departament_id" => 15],
            ["city_name" => "Cacahual", "departament_id" => 15],
            ["city_name" => "Pana Pana", "departament_id" => 15],
            ["city_name" => "Morichal", "departament_id" => 15]
        ];

        DB::table('cities')->insert($guainiaCities);

        $guaviareCities = [
            ["city_name" => "Calamar", "departament_id" => 16],
            ["city_name" => "San José del Guaviare", "departament_id" => 16],
            ["city_name" => "Miraflores", "departament_id" => 16],
            ["city_name" => "El Retorno", "departament_id" => 16]
        ];
        
        DB::table('cities')->insert($guaviareCities);

        $municipalities = [
            ['city_name' => 'Neiva', 'departament_id' => 17],
            ['city_name' => 'Acevedo', 'departament_id' => 17],
            ['city_name' => 'Agrado', 'departament_id' => 17],
            ['city_name' => 'Aipe', 'departament_id' => 17],
            ['city_name' => 'Algeciras', 'departament_id' => 17],
            ['city_name' => 'Altamira', 'departament_id' => 17],
            ['city_name' => 'Baraya', 'departament_id' => 17],
            ['city_name' => 'Campoalegre', 'departament_id' => 17],
            ['city_name' => 'Colombia', 'departament_id' => 17],
            ['city_name' => 'Elías', 'departament_id' => 17],
            ['city_name' => 'Garzón', 'departament_id' => 17],
            ['city_name' => 'Gigante', 'departament_id' => 17],
            ['city_name' => 'Guadalupe', 'departament_id' => 17],
            ['city_name' => 'Hobo', 'departament_id' => 17],
            ['city_name' => 'Iquira', 'departament_id' => 17],
            ['city_name' => 'Isnos', 'departament_id' => 17],
            ['city_name' => 'La Argentina', 'departament_id' => 17],
            ['city_name' => 'La Plata', 'departament_id' => 17],
            ['city_name' => 'Nátaga', 'departament_id' => 17],
            ['city_name' => 'Oporapa', 'departament_id' => 17],
            ['city_name' => 'Paicol', 'departament_id' => 17],
            ['city_name' => 'Palermo', 'departament_id' => 17],
            ['city_name' => 'Palestina', 'departament_id' => 17],
            ['city_name' => 'Pital', 'departament_id' => 17],
            ['city_name' => 'Pitalito', 'departament_id' => 17],
            ['city_name' => 'Rivera', 'departament_id' => 17],
            ['city_name' => 'Saladoblanco', 'departament_id' => 17],
            ['city_name' => 'Santa María', 'departament_id' => 17],
            ['city_name' => 'Suaza', 'departament_id' => 17],
            ['city_name' => 'Tarqui', 'departament_id' => 17],
            ['city_name' => 'Tesalia', 'departament_id' => 17],
            ['city_name' => 'Tello', 'departament_id' => 17],
            ['city_name' => 'Teruel', 'departament_id' => 17],
            ['city_name' => 'Timaná', 'departament_id' => 17],
            ['city_name' => 'Villavieja', 'departament_id' => 17],
            ['city_name' => 'Yaguará', 'departament_id' => 17],
            ['city_name' => 'San Agustín', 'departament_id' => 17],
            ['city_name' => 'Riohacha', 'departament_id' => 18],
            ['city_name' => 'Albania', 'departament_id' => 18],
            ['city_name' => 'Barrancas', 'departament_id' => 18],
            ['city_name' => 'Dibula', 'departament_id' => 18],
            ['city_name' => 'Distracción', 'departament_id' => 18],
            ['city_name' => 'El Molino', 'departament_id' => 18],
            ['city_name' => 'Fonseca', 'departament_id' => 18],
            ['city_name' => 'Hatonuevo', 'departament_id' => 18],
            ['city_name' => 'Maicao', 'departament_id' => 18],
            ['city_name' => 'Manaure', 'departament_id' => 18],
            ['city_name' => 'Uribia', 'departament_id' => 18],
            ['city_name' => 'Urumita', 'departament_id' => 18],
            ['city_name' => 'Villanueva', 'departament_id' => 18],
            ['city_name' => 'La Jagua del Pilar', 'departament_id' => 18],
            ['city_name' => 'San Juan del Cesar', 'departament_id' => 18],
            ['city_name' => 'Santa Marta', 'departament_id' => 19],
            ['city_name' => 'Algarrobo', 'departament_id' => 19],
            ['city_name' => 'Aracataca', 'departament_id' => 19],
            ['city_name' => 'Ariguaní', 'departament_id' => 19],
            ['city_name' => 'Cerro San Antonio', 'departament_id' => 19],
            ['city_name' => 'Chivolo', 'departament_id' => 19],
            ['city_name' => 'Concordia', 'departament_id' => 19],
            ['city_name' => 'El Banco', 'departament_id' => 19],
            ['city_name' => 'El Piñon', 'departament_id' => 19],
            ['city_name' => 'El Retén', 'departament_id' => 19],
            ['city_name' => 'Fundación', 'departament_id' => 19],
            ['city_name' => 'Guamal', 'departament_id' => 19],
            ['city_name' => 'Nueva Granada', 'departament_id' => 19],
            ['city_name' => 'Pedraza', 'departament_id' => 19],
            ['city_name' => 'Pivijay', 'departament_id' => 19],
            ['city_name' => 'Plato', 'departament_id' => 19],
            ['city_name' => 'Remolino', 'departament_id' => 19],
            ['city_name' => 'Salamina', 'departament_id' => 19],
            ['city_name' => 'San Zenón', 'departament_id' => 19],
            ['city_name' => 'Santa Ana', 'departament_id' => 19],
            ['city_name' => 'Sitionuevo', 'departament_id' => 19],
            ['city_name' => 'Tenerife', 'departament_id' => 19],
            ['city_name' => 'Zapayán', 'departament_id' => 19],
            ['city_name' => 'Zona Bananera', 'departament_id' => 19],
            ['city_name' => 'San Sebastián de Buenavista', 'departament_id' => 19],
            ['city_name' => 'Sabanas de San Angel', 'departament_id' => 19],
            ['city_name' => 'Pijiño del Carmen', 'departament_id' => 19],
            ['city_name' => 'Uribe', 'departament_id' => 20],
            ['city_name' => 'Villavicencio', 'departament_id' => 20],
            ['city_name' => 'Acacias', 'departament_id' => 20],
            ['city_name' => 'Cabuyaro', 'departament_id' => 20],
            ['city_name' => 'Cubarral', 'departament_id' => 20],
            ['city_name' => 'Cumaral', 'departament_id' => 20],
            ['city_name' => 'El Calvario', 'departament_id' => 20],
            ['city_name' => 'El Castillo', 'departament_id' => 20],
            ['city_name' => 'El Dorado', 'departament_id' => 20],
            ['city_name' => 'Granada', 'departament_id' => 20],
            ['city_name' => 'Guamal', 'departament_id' => 20],
            ['city_name' => 'Mapiripán', 'departament_id' => 20],
            ['city_name' => 'Mesetas', 'departament_id' => 20],
            ['city_name' => 'La Macarena', 'departament_id' => 20],
            ['city_name' => 'Lejanías', 'departament_id' => 20],
            ['city_name' => 'Puerto Concordia', 'departament_id' => 20],
            ['city_name' => 'Puerto Gaitán', 'departament_id' => 20],
            ['city_name' => 'Puerto López', 'departament_id' => 20],
            ['city_name' => 'Puerto Lleras', 'departament_id' => 20],
            ['city_name' => 'Puerto Rico', 'departament_id' => 20],
            ['city_name' => 'Restrepo', 'departament_id' => 20],
            ['city_name' => 'San Juanito', 'departament_id' => 20],
            ['city_name' => 'San Martín', 'departament_id' => 20],
            ['city_name' => 'Vista Hermosa', 'departament_id' => 20],
            ['city_name' => 'Barranca de Upía', 'departament_id' => 20],
            ['city_name' => 'Fuente de Oro', 'departament_id' => 20],
            ['city_name' => 'San Carlos de Guaroa', 'departament_id' => 20],
            ['city_name' => 'San Juan de Arama', 'departament_id' => 20],
            ['city_name' => 'Santacruz', 'departament_id' => 21],
            ['city_name' => 'Pasto', 'departament_id' => 21],
            ['city_name' => 'Albán', 'departament_id' => 21],
            ['city_name' => 'Aldana', 'departament_id' => 21],
            ['city_name' => 'Ancuyá', 'departament_id' => 21],
            ['city_name' => 'Barbacoas', 'departament_id' => 21],
            ['city_name' => 'Colón', 'departament_id' => 21],
            ['city_name' => 'Consaca', 'departament_id' => 21],
            ['city_name' => 'Contadero', 'departament_id' => 21],
            ['city_name' => 'Córdoba', 'departament_id' => 21],
            ['city_name' => 'Cuaspud', 'departament_id' => 21],
            ['city_name' => 'Cumbal', 'departament_id' => 21],
            ['city_name' => 'Cumbitara', 'departament_id' => 21],
            ['city_name' => 'El Charco', 'departament_id' => 21],
            ['city_name' => 'El Peñol', 'departament_id' => 21],
            ['city_name' => 'El Rosario', 'departament_id' => 21],
            ['city_name' => 'El Tambo', 'departament_id' => 21],
            ['city_name' => 'Funes', 'departament_id' => 21],
            ['city_name' => 'Guachucal', 'departament_id' => 21],
            ['city_name' => 'Guaitarilla', 'departament_id' => 21],
            ['city_name' => 'Gualmatán', 'departament_id' => 21],
            ['city_name' => 'Iles', 'departament_id' => 21],
            ['city_name' => 'Imués', 'departament_id' => 21],
            ['city_name' => 'Ipiales', 'departament_id' => 21],
            ['city_name' => 'La Cruz', 'departament_id' => 21],
            ['city_name' => 'La Florida', 'departament_id' => 21],
            ['city_name' => 'La Llanada', 'departament_id' => 21],
            ['city_name' => 'La Tola', 'departament_id' => 21],
            ['city_name' => 'La Unión', 'departament_id' => 21],
            ['city_name' => 'Leiva', 'departament_id' => 21],
            ['city_name' => 'Linares', 'departament_id' => 21],
            ['city_name' => 'Los Andes', 'departament_id' => 21],
            ['city_name' => 'Magüí', 'departament_id' => 21],
            ['city_name' => 'Mallama', 'departament_id' => 21],
            ['city_name' => 'Mosquera', 'departament_id' => 21],
            ['city_name' => 'Nariño', 'departament_id' => 21],
            ['city_name' => 'Olaya Herrera', 'departament_id' => 21],
            ['city_name' => 'Ospina', 'departament_id' => 21],
            ['city_name' => 'Francisco Pizarro', 'departament_id' => 21],
            ['city_name' => 'Policarpa', 'departament_id' => 21],
            ['city_name' => 'Potosí', 'departament_id' => 21],
            ['city_name' => 'Providencia', 'departament_id' => 21],
            ['city_name' => 'Puerres', 'departament_id' => 21],
            ['city_name' => 'Pupiales', 'departament_id' => 21],
            ['city_name' => 'Ricaurte', 'departament_id' => 21],
            ['city_name' => 'Roberto Payán', 'departament_id' => 21],
            ['city_name' => 'Samaniego', 'departament_id' => 21],
            ['city_name' => 'Sandoná', 'departament_id' => 21],
            ['city_name' => 'San Bernardo', 'departament_id' => 21],
            ['city_name' => 'San Lorenzo', 'departament_id' => 21],
            ['city_name' => 'San Pablo', 'departament_id' => 21],
            ['city_name' => 'Santa Bárbara', 'departament_id' => 21],
            ['city_name' => 'Sapuyes', 'departament_id' => 21],
            ['city_name' => 'Taminango', 'departament_id' => 21],
            ['city_name' => 'Tangua', 'departament_id' => 21],
            ['city_name' => 'Túquerres', 'departament_id' => 21],
            ['city_name' => 'Yacuanquer', 'departament_id' => 21],
            ['city_name' => 'San Pedro de Cartago', 'departament_id' => 21],
            ['city_name' => 'El Tablón de Gómez', 'departament_id' => 21],
            ['city_name' => 'Cucuta', 'departament_id' => 22],
            ['city_name' => 'Silos', 'departament_id' => 22],
            ['city_name' => 'Cácota', 'departament_id' => 22],
            ['city_name' => 'Toledo', 'departament_id' => 22],
            ['city_name' => 'Mutiscua', 'departament_id' => 22],
            ['city_name' => 'El Zulia', 'departament_id' => 22],
            ['city_name' => 'Salazar', 'departament_id' => 22],
            ['city_name' => 'Cucutilla', 'departament_id' => 22],
            ['city_name' => 'Puerto Santander', 'departament_id' => 22],
            ['city_name' => 'Gramalote', 'departament_id' => 22],
            ['city_name' => 'El Tarra', 'departament_id' => 22],
            ['city_name' => 'Teorama', 'departament_id' => 22],
            ['city_name' => 'Arboledas', 'departament_id' => 22],
            ['city_name' => 'Ocaña', 'departament_id' => 22],
            ['city_name' => 'Mocoa', 'departament_id' => 23],
            ['city_name' => 'Colón', 'departament_id' => 23],
            ['city_name' => 'Orito', 'departament_id' => 23],
            ['city_name' => 'Puerto Caicedo', 'departament_id' => 23],
            ['city_name' => 'Puerto Guzmán', 'departament_id' => 23],
            ['city_name' => 'Leguízamo', 'departament_id' => 23],
            ['city_name' => 'Sibundoy', 'departament_id' => 23],
            ['city_name' => 'San Francisco', 'departament_id' => 23],
            ['city_name' => 'San Miguel', 'departament_id' => 23],
            ['city_name' => 'Santiago', 'departament_id' => 23],
            ['city_name' => 'Valle de Guamez', 'departament_id' => 23],
            ['city_name' => 'Armenia', 'departament_id' => 24],
            ['city_name' => 'Buenavista', 'departament_id' => 24],
            ['city_name' => 'Circasia', 'departament_id' => 24],
            ['city_name' => 'Córdoba', 'departament_id' => 24],
            ['city_name' => 'Filandia', 'departament_id' => 24],
            ['city_name' => 'La Tebaida', 'departament_id' => 24],
            ['city_name' => 'Montenegro', 'departament_id' => 24],
            ['city_name' => 'Pijao', 'departament_id' => 24],
            ['city_name' => 'Quimbaya', 'departament_id' => 24],
            ['city_name' => 'Salento', 'departament_id' => 24],
            ['city_name' => 'Pereira', 'departament_id' => 25],
            ['city_name' => 'Apía', 'departament_id' => 25],
            ['city_name' => 'Balboa', 'departament_id' => 25],
            ['city_name' => 'Dosquebradas', 'departament_id' => 25],
            ['city_name' => 'Guática', 'departament_id' => 25],
            ['city_name' => 'La Celia', 'departament_id' => 25],
            ['city_name' => 'La Virginia', 'departament_id' => 25],
            ['city_name' => 'Marsella', 'departament_id' => 25],
            ['city_name' => 'Mistrató', 'departament_id' => 25],
            ['city_name' => 'Pueblo Rico', 'departament_id' => 25],
            ['city_name' => 'Quinchía', 'departament_id' => 25],
            ['city_name' => 'Santuario', 'departament_id' => 25],
            ['city_name' => 'Santa Rosa de Cabal', 'departament_id' => 25],
            ['city_name' => 'Belén de Umbría', 'departament_id' => 25],
            ['city_name' => 'Providencia', 'departament_id' => 26],
            ['city_name' => 'San Andrés', 'departament_id' => 26],
            ['city_name' => 'Puerto Wilches', 'departament_id' => 27],
            ['city_name' => 'Puerto Parra', 'departament_id' => 27],
            ['city_name' => 'Bucaramanga', 'departament_id' => 27],
            ['city_name' => 'Aguada', 'departament_id' => 27],
            ['city_name' => 'Albania', 'departament_id' => 27],
            ['city_name' => 'Aratoca', 'departament_id' => 27],
            ['city_name' => 'Barbosa', 'departament_id' => 27],
            ['city_name' => 'Barichara', 'departament_id' => 27],
            ['city_name' => 'Barrancabermeja', 'departament_id' => 27],
            ['city_name' => 'Betulia', 'departament_id' => 27],
            ['city_name' => 'Bolívar', 'departament_id' => 27],
            ['city_name' => 'Cabrera', 'departament_id' => 27],
            ['city_name' => 'California', 'departament_id' => 27],
            ['city_name' => 'Carcasí', 'departament_id' => 27],
            ['city_name' => 'Cepitá', 'departament_id' => 27],
            ['city_name' => 'Cerrito', 'departament_id' => 27],
            ['city_name' => 'Charalá', 'departament_id' => 27],
            ['city_name' => 'Charta', 'departament_id' => 27],
            ['city_name' => 'Chipatá', 'departament_id' => 27],
            ['city_name' => 'Cimitarra', 'departament_id' => 27],
            ['city_name' => 'Concepción', 'departament_id' => 27],
            ['city_name' => 'Confines', 'departament_id' => 27],
            ['city_name' => 'Contratación', 'departament_id' => 27],
            ['city_name' => 'Coromoro', 'departament_id' => 27],
            ['city_name' => 'Curití', 'departament_id' => 27],
            ['city_name' => 'El Guacamayo', 'departament_id' => 27],
            ['city_name' => 'El Playón', 'departament_id' => 27],
            ['city_name' => 'Encino', 'departament_id' => 27],
            ['city_name' => 'Enciso', 'departament_id' => 27],
            ['city_name' => 'Florián', 'departament_id' => 27],
            ['city_name' => 'Floridablanca', 'departament_id' => 27],
            ['city_name' => 'Galán', 'departament_id' => 27],
            ['city_name' => 'Gambita', 'departament_id' => 27],
            ['city_name' => 'Girón', 'departament_id' => 27],
            ['city_name' => 'Guaca', 'departament_id' => 27],
            ['city_name' => 'Guadalupe', 'departament_id' => 27],
            ['city_name' => 'Guapotá', 'departament_id' => 27],
            ['city_name' => 'Guavatá', 'departament_id' => 27],
            ['city_name' => 'Güepsa', 'departament_id' => 27],
            ['city_name' => 'Jesús María', 'departament_id' => 27],
            ['city_name' => 'Jordán', 'departament_id' => 27],
            ['city_name' => 'La Belleza', 'departament_id' => 27],
            ['city_name' => 'Landázuri', 'departament_id' => 27],
            ['city_name' => 'La Paz', 'departament_id' => 27],
            ['city_name' => 'Lebríja', 'departament_id' => 27],
            ['city_name' => 'Los Santos', 'departament_id' => 27],
            ['city_name' => 'Macaravita', 'departament_id' => 27],
            ['city_name' => 'Málaga', 'departament_id' => 27],
            ['city_name' => 'Matanza', 'departament_id' => 27],
            ['city_name' => 'Mogotes', 'departament_id' => 27],
            ['city_name' => 'Molagavita', 'departament_id' => 27],
            ['city_name' => 'Ocamonte', 'departament_id' => 27],
            ['city_name' => 'Oiba', 'departament_id' => 27],
            ['city_name' => 'Onzaga', 'departament_id' => 27],
            ['city_name' => 'Palmar', 'departament_id' => 27],
            ['city_name' => 'Páramo', 'departament_id' => 27],
            ['city_name' => 'Piedecuesta', 'departament_id' => 27],
            ['city_name' => 'Pinchote', 'departament_id' => 27],
            ['city_name' => 'Puente Nacional', 'departament_id' => 27],
            ['city_name' => 'Rionegro', 'departament_id' => 27],
            ['city_name' => 'San Andrés', 'departament_id' => 27],
            ['city_name' => 'San Gil', 'departament_id' => 27],
            ['city_name' => 'San Joaquín', 'departament_id' => 27],
            ['city_name' => 'San Miguel', 'departament_id' => 27],
            ['city_name' => 'Santa Bárbara', 'departament_id' => 27],
            ['city_name' => 'Simacota', 'departament_id' => 27],
            ['city_name' => 'Socorro', 'departament_id' => 27],
            ['city_name' => 'Suaita', 'departament_id' => 27],
            ['city_name' => 'Sucre', 'departament_id' => 27],
            ['city_name' => 'Suratá', 'departament_id' => 27],
            ['city_name' => 'Tona', 'departament_id' => 27],
            ['city_name' => 'Vélez', 'departament_id' => 27],
            ['city_name' => 'Vetas', 'departament_id' => 27],
            ['city_name' => 'Villanueva', 'departament_id' => 27],
            ['city_name' => 'Zapatoca', 'departament_id' => 27],
            ['city_name' => 'Palmas del Socorro', 'departament_id' => 27],
            ['city_name' => 'San Vicente de Chucurí', 'departament_id' => 27],
            ['city_name' => 'San José de Miranda', 'departament_id' => 27],
            ['city_name' => 'Santa Helena del Opón', 'departament_id' => 27],
            ['city_name' => 'Sabana de Torres', 'departament_id' => 27],
            ['city_name' => 'El Carmen de Chucurí', 'departament_id' => 27],
            ['city_name' => 'Valle de San José', 'departament_id' => 27],
            ['city_name' => 'San Benito', 'departament_id' => 27],
            ['city_name' => 'Hato', 'departament_id' => 27],
            ['city_name' => 'Sincelejo', 'departament_id' => 28],
            ['city_name' => 'Buenavista', 'departament_id' => 28],
            ['city_name' => 'Caimito', 'departament_id' => 28],
            ['city_name' => 'Coloso', 'departament_id' => 28],
            ['city_name' => 'Coveñas', 'departament_id' => 28],
            ['city_name' => 'Chalán', 'departament_id' => 28],
            ['city_name' => 'El Roble', 'departament_id' => 28],
            ['city_name' => 'Galeras', 'departament_id' => 28],
            ['city_name' => 'Guaranda', 'departament_id' => 28],
            ['city_name' => 'La Unión', 'departament_id' => 28],
            ['city_name' => 'Los Palmitos', 'departament_id' => 28],
            ['city_name' => 'Majagual', 'departament_id' => 28],
            ['city_name' => 'Morroa', 'departament_id' => 28],
            ['city_name' => 'Ovejas', 'departament_id' => 28],
            ['city_name' => 'Palmito', 'departament_id' => 28],
            ['city_name' => 'San Benito Abad', 'departament_id' => 28],
            ['city_name' => 'San Marcos', 'departament_id' => 28],
            ['city_name' => 'San Onofre', 'departament_id' => 28],
            ['city_name' => 'San Pedro', 'departament_id' => 28],
            ['city_name' => 'Sucre', 'departament_id' => 28],
            ['city_name' => 'Tolú Viejo', 'departament_id' => 28],
            ['city_name' => 'San Luis de Sincé', 'departament_id' => 28],
            ['city_name' => 'San Juan de Betulia', 'departament_id' => 28],
            ['city_name' => 'Santiago de Tolú', 'departament_id' => 28],
            ['city_name' => 'Alpujarra', 'departament_id' => 29],
            ['city_name' => 'Alvarado', 'departament_id' => 29],
            ['city_name' => 'Ambalema', 'departament_id' => 29],
            ['city_name' => 'Armero', 'departament_id' => 29],
            ['city_name' => 'Ataco', 'departament_id' => 29],
            ['city_name' => 'Cajamarca', 'departament_id' => 29],
            ['city_name' => 'Chaparral', 'departament_id' => 29],
            ['city_name' => 'Coello', 'departament_id' => 29],
            ['city_name' => 'Coyaima', 'departament_id' => 29],
            ['city_name' => 'Cunday', 'departament_id' => 29],
            ['city_name' => 'Dolores', 'departament_id' => 29],
            ['city_name' => 'Espinal', 'departament_id' => 29],
            ['city_name' => 'Falan', 'departament_id' => 29],
            ['city_name' => 'Flandes', 'departament_id' => 29],
            ['city_name' => 'Fresno', 'departament_id' => 29],
            ['city_name' => 'Guamo', 'departament_id' => 29],
            ['city_name' => 'Herveo', 'departament_id' => 29],
            ['city_name' => 'Honda', 'departament_id' => 29],
            ['city_name' => 'Icononzo', 'departament_id' => 29],
            ['city_name' => 'Mariquita', 'departament_id' => 29],
            ['city_name' => 'Melgar', 'departament_id' => 29],
            ['city_name' => 'Murillo', 'departament_id' => 29],
            ['city_name' => 'Natagaima', 'departament_id' => 29],
            ['city_name' => 'Ortega', 'departament_id' => 29],
            ['city_name' => 'Palocabildo', 'departament_id' => 29],
            ['city_name' => 'Piedras', 'departament_id' => 29],
            ['city_name' => 'Planadas', 'departament_id' => 29],
            ['city_name' => 'Prado', 'departament_id' => 29],
            ['city_name' => 'Purificación', 'departament_id' => 29],
            ['city_name' => 'Rio Blanco', 'departament_id' => 29],
            ['city_name' => 'Roncesvalles', 'departament_id' => 29],
            ['city_name' => 'Rovira', 'departament_id' => 29],
            ['city_name' => 'Saldaña', 'departament_id' => 29],
            ['city_name' => 'Santa Isabel', 'departament_id' => 29],
            ['city_name' => 'Venadillo', 'departament_id' => 29],
            ['city_name' => 'Villahermosa', 'departament_id' => 29],
            ['city_name' => 'Villarrica', 'departament_id' => 29],
            ['city_name' => 'Valle de San Juan', 'departament_id' => 29],
            ['city_name' => 'Carmen de Apicala', 'departament_id' => 29],
            ['city_name' => 'San Luis', 'departament_id' => 29],
            ['city_name' => 'San Antonio', 'departament_id' => 29],
            ['city_name' => 'El Dovio', 'departament_id' => 30],
            ['city_name' => 'Roldanillo', 'departament_id' => 30],
            ['city_name' => 'Argelia', 'departament_id' => 30],
            ['city_name' => 'Sevilla', 'departament_id' => 30],
            ['city_name' => 'Zarzal', 'departament_id' => 30],
            ['city_name' => 'El Cerrito', 'departament_id' => 30],
            ['city_name' => 'Cartago', 'departament_id' => 30],
            ['city_name' => 'Caicedonia', 'departament_id' => 30],
            ['city_name' => 'El Cairo', 'departament_id' => 30],
            ['city_name' => 'La Unión', 'departament_id' => 30],
            ['city_name' => 'Restrepo', 'departament_id' => 30],
            ['city_name' => 'Dagua', 'departament_id' => 30],
            ['city_name' => 'Guacarí', 'departament_id' => 30],
            ['city_name' => 'Mitú', 'departament_id' => 31],
            ['city_name' => 'Carurú', 'departament_id' => 31],
            ['city_name' => 'Taraira', 'departament_id' => 31],
            ['city_name' => 'Papunahua', 'departament_id' => 31],
            ['city_name' => 'Yavaraté', 'departament_id' => 31],
            ['city_name' => 'Pacoa', 'departament_id' => 31],
            ['city_name' => 'Puerto Carreño', 'departament_id' => 32],
            ['city_name' => 'La Primavera', 'departament_id' => 32],
            ['city_name' => 'Santa Rosalía', 'departament_id' => 32],
            ['city_name' => 'Cumaribo', 'departament_id' => 32],
        ];


        DB::table('cities')->insert($municipalities);

    }
    }